[package]
name = "ctclsite-rust"
version = "1.1.0"
license = "MIT"
edition = "2021"

[dependencies]
rocket = "0.5.0"
tera = "1.19.1"

[dependencies.rocket_dyn_templates]
version = "0.1.0"
features = ["tera"]