[package]
name = "ctclsite"
version = "0.1.1"
license = "MIT"
edition = "2021"

[dependencies]
tera = "1.17.1"
actix-web = "4.2.1"
actix-files = "0.6.2"
flate2 = "1.0.25"
pulldown-cmark = { version = "0.9.2", default-features = false }
ignore = "0.4.18"
toml = "0.5.10"
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.91"
once_cell = "1.17.0"
csv = "1.1.6"
comrak = "0.15.0"
indexmap = { version = "1.9.2", features = ["serde-1"] }
minifier = "0.2.2"
