[package]
name = "ctclsite-rust"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
tera = "1"
actix-web = "4"
env_logger = "0.9.0"
actix-files = "0.6.1"
pulldown-cmark = { version = "0.9.1", default-features = false }
ignore = "0.4"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.16.0"
csv = "1.1"
comrak = "0.15.0"