[package]
name = "ctclsite"
version = "0.3.0"
license = "MIT"
edition = "2021"

[dependencies]
tera = "1.18.1"
actix-web = "4.3.1"
actix-files = "0.6.2"
flate2 = "1.0.25"
pulldown-cmark = { version = "0.9.2", default-features = false }
ignore = "0.4.20"
toml = "0.7.3"
serde = "1.0.160"
serde_derive = "1.0.160"
serde_json = "1.0.96"
once_cell = "1.17.1"
csv = "1.2.1"
comrak = "0.18.0"
indexmap = { version = "1.9.3", features = ["serde-1"] }
minifier = "0.2.2"
env_logger = "0.10.0"
