[package]
name = "ctclsite"
version = "1.1.0"
license = "MIT"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
actix-web-lab = "0.20.2"
log = "0.4.20"
serde = "1.0.197"
serde_json = "1.0.114"
simple-logging = "2.0.2"
tera = "1.19.1"