#!/bin/bash
# ctclsite-rust - CTCL 2020-2024
# File: mkrelease
# Purpose: Builds and gathers files
# Created: March 4, 2024
# Modified: September 18, 2024

# Intentionally left blank for the time being
