#!/bin/bash
# ctclsite-rust - CTCL 2022-2024
# File: mkrelease
# Purpose: Builds and gathers files
# Created: March 4, 2024
# Modified: March 23, 2024

if [ ! -f Cargo.toml ]; then
    echo "Cargo.toml not found in the current directory. Make sure this script is being run within the ctclsite-rust directory."
    exit
fi

rm release.tar.gz

if [[ $* == *--content-only* ]]
then
    tar -czvf release.tar.gz config static
else 
    rm target/release/ctclsite
    
    if cargo build --profile release ; then
        cp target/release/ctclsite ./ctclsite
        tar -czvf release.tar.gz ctclsite config templates static
        rm ./ctclsite
    else
        echo "Cargo build failed"
        exit
    fi
fi


