- model: "MX440 Daytona"
  gpvnd: "Nvidia"
  gpmdl: 
  bustp: "AGP"
  vidcn:
  memtp: "DDR"
  memtc: "64 MByte"
  membw: "128-bit"
  membs: ""
  memog: "8 ICs x 16-bit"
  memiv: "Samsung"
  memib: "Samsung"
  memic: "64 Mbit"
  memim: "K4D64163HF-TC40 (Die code: U9GB27DA KOREA, Date: 235, Week 25, 2002)"
  memip: "TSOP-66"
  othic:
  htsnk: "Passive ALU Heatsink"
  notes: 
  insrc: "Kris (pictures, memory info, card info), CrazyblocksTechnologies (Confirmation, more IC info)"
