- model: "Arc A380"
  gpvnd: "Intel"
  gpmdl: "ACM-G11"
  bustp: "PCIe 4.0 x8"
  vidcn: "3x DisplayPort, 1x HDMI"
  memtp: "GDDR6"
  memtc: "6 GByte"
  membw: "96-bit"
  membs: "2000 MHz"
  memog: "3 ICs x 32-bit"
  memiv: "Samsung"
  memib: "Samsung"
  memic: "16 Gbit"
  memim: "K4ZAF325BM-HC16" 
  memip: "BGA"
  othic: "Sinopower SM4507NHKP; 7212; Monolithic Power Systems M2940"
  htsnk: "Two fans with aluminum heatsink"
  notes: "Likely half of the PCIe pairs are disconnected on the PCB due to the x8 interface on the GPU"
  insrc: "TechPowerUp https://www.techpowerup.com/review/intel-arc-a380/2.html (Interface), https://www.techpowerup.com/review/intel-arc-a380/4.html (ICs)"
