- model: "Radeon RX 6950 XT OC"
  gpvnd: "AMD"
  gpmdl: "Navi 21 RDNA2"
  bustp: "PCIe x16"
  vidcn: "3x DisplayPort 1.4, HDMI 2.1"
  memtp: "GDDR6"
  memtc: "16 GByte"
  membw: "256-bit"
  membs: "2250 MHz"
  memog: "8 ICs x 32-bit"
  memiv: "Samsung"
  memib: "Samsung"
  memic: "16 Gbit"
  memim: "K4ZAF325BM-HC18"
  memip: BGA
  othic: "Infineon XDPE132G5D; IOR/Infineon TDA21490; IOR/Infineon IRF35217; IOR/Infineon TDA21472"
  htsnk: "Aluminum heatsink with three fans"
  notes: "GPU has 18 power phases, memory has 3 power phases"
  insrc: "TechPowerUp https://www.techpowerup.com/review/asrock-radeon-rx-6950-xt-oc-formula/2.html (Connectors, Heatsink), https://www.techpowerup.com/review/asrock-radeon-rx-6950-xt-oc-formula/3.html (ICs)"
