- model: "GT 730 DDR3"
  gpvnd: "Nvidia"
  gpmdl: "GK208B"
  bustp: "PCIe 2.0 x8"
  vidcn: "1x DisplayPort, 1x DVI-I"
  memtp: "DDR3"
  memtc: "2 GByte"
  membw: "64-bit"
  membs: "DDR3-1866"
  memog: "4 ICs, 16-bit"
  memiv: "SK hynix"
  memib: "SK hynix"
  memic: "4 Gbit"
  memim: "Possibly H5TC4G63x"
  memip: "FBGA-96"
  othic:
  htsnk: "Aluminum heatsink painted black, red PBT fan"
  notes: "Low-profile capability"
  insrc: "CrazyblocksTechnologies Computer Laboratories (memory IC vendor), Icecat (memory bus info): https://icecat.biz/en/p/hp/z9h51aa/graphics+cards-0190780959404-nvidia+gt+730+2gb+dp+card-35836539.html, SK hynix (part number info): https://product.skhynix.com/products/dram/ddr.go"
