- model: "GeForce GTX 1630 Ghost"
  gpvnd: "Nvidia"
  gpmdl: "TU117 \"Turing\""
  bustp: "PCIe 3.0 x16"
  vidcn: "2x DisplayPort 1.4, 1x HDMI 2.0b"
  memtp: "GDDR6"
  memtc: "4 GByte"
  membw: "64-bit"
  membs: "2000 MHz"
  memog: "2 ICs x 32 bit"
  memiv: "SK hynix"
  memib: "SK hynix"
  memic: "16 Gbit"
  memim: "H56G42AS4DX014"
  memip: BGA
  othic: "Richtek RT8813D; Sinopower SM4503NHKP MOSFET; 7212"
  htsnk: "Two fans, aluminum heatsink with pads for VRM, memory and GPU"
  notes: "Two phase GPU power, two extra GDDR6 BGA footprints unpopulated"
  insrc: "TechPowerUp https://www.techpowerup.com/review/gainward-geforce-gtx-1630-ghost/3.html (ICs), https://www.techpowerup.com/review/gainward-geforce-gtx-1630-ghost/37.html (PCIe revision), https://www.techpowerup.com/review/gainward-geforce-gtx-1630-ghost/2.html (Video connectors)" 
