[build]
# Change the "target-cpu" parameter to whatever CPU you need to support.
rustflags = ["-C", "target-cpu=westmere"]

[term]
quiet = false
verbose = false
hyperlinks = true      # whether cargo inserts links into output
progress.when = 'auto' # whether cargo shows progress bar
progress.width = 80    # width of progress bar