- model: "HD 5450"
  gpvnd: "AMD/ATI"
  gpmdl: "Cedar PRO"
  bustp: "PCIe 2.0 x16"
  vidcn: "1x DVI-I, 1x HDMI 1.3a, 1x VGA (not available on Low-profile bracket)"
  memtp: "DDR3"
  memtc: "1 GByte"
  membw: "64-bit"
  membs: "DDR3-1600"
  memog: "4 ICs x 16-bit"
  memiv: "Micron"
  memib: "AMD"
  memic: "2 Gbit"
  memim: "D9PLN 23EY4187MA12 (Die code: 57HG, Date Code: 1144; Week 44, 2011"
  memip: ""
  othic: 
  htsnk: "TechPowerUp's picture shows a passively cooled heatink painted black, most likely made from aluminum. Kris's unit has a passive heatsink also."
  notes: 
  insrc: "Kris (pictures, memory info, card info), CrazyblocksTechnologies (Confirmation, more IC info), TechPowerUp (more card info) https://www.techpowerup.com/gpu-specs/sapphire-hd-5450-hypermemory-lp-1-gb.b733"
- model: "R5 230"
  gpvnd: "AMD/ATI"
  gpmdl: "Caicos PRO"
  bustp: "PCIe 2.0 x16"
  vidcn: "1x DVI-I, 1x HDMI 1.3a, 1x VGA (not available on Low-profile bracket)"
  memtp: "DDR3"
  memtc: "1 GByte"
  membw: "64-bit"
  membs: "DDR3-1333"
  memog: "4 ICs x 16-bit"
  memiv: "Nanya"
  memib: "Nanya"
  memic: "2 Gbit"
  memim: "NT5CB128M16IP-EK (Die code: 607181W0EF 7 TW, Date code: 1617; Week 17, 2016)"
  memip: 
  othic: 
  htsnk: "TechPowerUp's picture shows a passively cooled heatink painted black, most likely made from aluminum. Kris's unit has a passive heatsink also."
  notes: 
  insrc: "Kris (pictures, memory info, card info), CrazyblocksTechnologies (Confirmation, more IC info), TechPowerUp (more card info) https://www.techpowerup.com/gpu-specs/sapphire-r5-230.b2896"
- model: "R9 390 Nitro w/Backplate"
  gpvnd: "AMD/ATI"
  gpmdl: "Grenada PRO (215-0880030)"
  bustp: "PCIe 3.0 x16"
  vidcn: "1x DVI, 1x HDMI 1.4a, 3x DisplayPort 1.2"
  memtp: "GDDR5"
  memtc: "8 GByte"
  membw: "512-bit"
  membs: "GDDR5-6000 (1500 MHz)"
  memog: "16 ICs x 32-bit"
  memiv: "SK hynix"
  memib: "SK hynix"
  memic: "4 Gbit"
  memim: "H5GC4H24AJR (Die code: VWMH1728WY1, Location: ROC; China, Date code: 639V; Week 39, 2016)"
  memip: 
  othic: 
  htsnk: "Three fans" 
  notes: 
  insrc: "Kris (pictures, memory info, card info), CrazyblocksTechnologies (Confirmation, more IC info), TechPowerUp (more card info) https://www.techpowerup.com/gpu-specs/sapphire-nitro-r9-390.b3357" 
- model: "R7 250E"
  gpvnd: "AMD/ATI"
  gpmdl: "Cape Verde PRO"
  bustp: "PCIe 3.0 x16"
  vidcn: "1x DVI, 1x HDMI 1.4a, 1x DisplayPort 1.2"
  memtp: "GDDR5"
  memtc: "2 GByte"
  membw: "128-bit"
  membs: "GDDR5-4500"
  memog: "4 ICs x 32-bit"
  memiv: "Samsung"
  memib: "Samsung"
  memic: "4 Gbit"
  memim: "K4G41325FS-HC03 (Die code: G21H8101A, Date code: 610; Week 10, 2016)"
  memip: 
  othic: 
  htsnk: "TechPowerUp's picture shows heatsink with blue PBT fan with Sapphire logo sticker. Kris's unit has an extruded aluminium heatsink, no heatpipes and a 60mm fan with shroud"
  notes: 
  insrc: "Kris (pictures, memory info, card info), CrazyblocksTechnologies (Confirmation, more IC info), TechPowerUp (more card info) https://www.techpowerup.com/gpu-specs/sapphire-r7-250e-oc-2-gb.b5396"
