- model: "GeForce RTX 3080 Noctua OC"
  gpvnd: "Nvidia"
  gpmdl: "GA102 (LHR)"
  bustp: "PCIe 4.0 x16"
  vidcn: "3x DisplayPort 1.4, 2x HDMI 2.1"
  memtp: "GDDR6X"
  memtc: "10 GByte"
  membw: "320-bit"
  membs: "2376 MHz"
  memog: "10 ICs x 32-bit"
  memiv: "Micron"
  memib: "Micron"
  memic: "8 Gbit"
  memim: "MT61K256M32JE-19G:T D8BWW"
  memip: BGA
  othic: "UPI uP9512R; Vishay Siliconix SiC654 DrMOS; UPI uP9512S; Vishay Siliconix SiC654 DrMOS"
  htsnk: "Two Noctua NF-A12x25 120mm standard size, aluminum heatsink" 
  notes: "Two uP9512R ICs are used for 16-phase power for the GPU, memory power is 4-phase. Two GDDR6X BGA footprints unpopulated."
  insrc: "TechPowerUp https://www.techpowerup.com/review/asus-geforce-rtx-3080-noctua-oc/2.html (Fans, video connectors), https://www.techpowerup.com/review/asus-geforce-rtx-3080-noctua-oc/3.html (ICs), https://www.techpowerup.com/review/asus-geforce-rtx-3080-noctua-oc/37.html (PCIe version)"
