- model: "Radeon RX 6950 XT Reference Design"
  gpvnd: "AMD"
  gpmdl: "Navi 21"
  bustp: "PCIe 4.0 x16"
  vidcn: "2x DisplayPort 1.4, 1x HDMI 2.1, 1x USB Type-C (DisplayPort)"
  memtp: "GDDR6"
  memtc: "16 GByte"
  membw: "256-bit"
  membs: "2250 MHz"
  memog: "8 ICs x 32-bit"
  memiv: "Samsung"
  memib: "Samsung"
  memic: "16 Gbit"
  memim: "K4ZAF325BM-HC18"
  memip: "BGA"
  othic: 
  htsnk: "Three fans with aluminum heatsink"
  notes: 
  insrc: "TechPowerUp https://www.techpowerup.com/review/amd-radeon-rx-6950-xt-reference-design/2.html (Video connectors); https://www.techpowerup.com/review/amd-radeon-rx-6950-xt-reference-design/2.html (Memory IC)"
