- model: "HD 6510"
  gpvnd: "AMD/ATI"
  gpmdl: "Turks LE"
  bustp: "PCIe 2.0 x16"
  vidcn: "1x DVI-I, 1x HDMI 1.3a, 1x VGA"
  memtp: "GDDR3"
  memtc: "1 GByte"
  membw: "128-bit"
  membs: "GDDR3-1000"
  memog: "8 ICs x 16-bit"
  memiv: "PSC/Powerchip"
  memib: "Mezza"
  memic: "512 Mbit"
  memim: "PSC PN unknown, Mezza Z3P1GF3FGF1131G-GDJ (Die code: XFM809A3G-A)"
  memip: "FBGA-84(?)"
  othic:
  htsnk: "GPU most likely has a fan and an aluminum heatsink. Kris's unit has a small heatsink with a 40mm fan with shroud."
  notes: "Die code style and placement signifies PSC/Powerchip." 
  insrc: "Kris (pictures, memory info, card info), CrazyblocksTechnologies (Confirmation, more IC info), TechPowerUp https://www.techpowerup.com/gpu-specs/radeon-hd-6510.c2067"
